### ISSUE TITLE
support css support synatx

### ISSUE THREAD

**Issue by SGAMERyu** [Tahul/pinceau#79]
Sometimes CSS properties provide us with query syntax, such as 'support'. What if we combine this approach with props for responsive design?

And here's a polished version of the English translation:

At times, CSS properties offer us query syntax like 'support'. How about we incorporate this approach with props for a more responsive design?
```css
@supports (aspect-ratio: props.ratio) {
  .container {
    aspect-ratio: 16 / 9;
  }
}
```
